### ISSUE TITLE
Update and improve demo project

### ISSUE THREAD

**Issue by vmarcosp** [rescriptbr/reform#227]
## TODO
- [x] Upgrade rescript, rescript-react and reform version
- [x] Clean and refine reform examples
- [x] Improve layout with `@rescriptbr/ancestor`
